DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR            NOT NULL,
    email        VARCHAR            NOT NULL,
    password     VARCHAR            NOT NULL,
    enabled      BOOLEAN            NOT NULL,
    initial      VARCHAR(1)         NOT NULL,
    color        VARCHAR            NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
    user_id      INTEGER        NOT NULL,
    role         VARCHAR,
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE posts
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR            NOT NULL,
    text         VARCHAR            NOT NULL,
    date         TIMESTAMP          NOT NULL,
    show         INTEGER            NOT NULL,
    comments     INTEGER            NOT NULL,
    user_id      INTEGER            NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);